import {test,expect} from 'bun:test';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ArchiveQueue,applyArchiveBatch,type ArchiveConversation} from '../src/archive';
import {MemoryStore} from '../src/store';
import {sqliteDatabase} from '../src/database';
const sample:ArchiveConversation={threadId:'example-thread',title:'测试会话',cwd:'example-project',createdAt:'2026-10-07T00:00:00Z',entries:[{id:'user-1',time:'2026-10-07T00:00:00Z',type:'user',text:'这是历史基线'}]};
function setup(){const dir=mkdtempSync(join(tmpdir(),'membridge-archive-'));const file=join(dir,'queue.db');const q=new ArchiveQueue(file);return {q,file,close(){this.q.close();if(!dir.startsWith(join(tmpdir(),'membridge-archive-')))throw new Error('INVALID_TEST_DIRECTORY');rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:50})}}}
test('baseline and unchanged snapshots produce no duplicate archive records',()=>{const s=setup();try{s.q.seed(sample,['aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa']);expect(s.q.capture(sample,'fingerprint-1')).toBe(0);expect(s.q.pending()).toBeNull();expect(s.q.needsCapture(sample.threadId,'fingerprint-1')).toBe(false)}finally{s.close()}});
test('new items remain durable offline, acknowledge only a matching batch, and deduplicate after restart',()=>{const s=setup();try{s.q.seed(sample,[]);const next={...sample,entries:[...sample.entries,{id:'assistant-1',time:'2026-10-07T00:01:00Z',type:'assistant',phase:'final_answer',text:'Authorization: Bearer private-token-value'}]};expect(s.q.capture(next,'v2')).toBeGreaterThan(0);const pending=s.q.pending()!;expect(pending.requests[0].memory.body).not.toContain('private-token-value');s.q.close();s.q=new ArchiveQueue(s.file);expect(s.q.pending()?.id).toBe(pending.id);expect(s.q.capture(next,'v3')).toBe(0);expect(()=>s.q.acknowledge(pending.id,'wrong-hash')).toThrow();expect(s.q.pending()).not.toBeNull();s.q.acknowledge(pending.id,pending.sha256);expect(s.q.pending()).toBeNull()}finally{s.close()}});
test('revisions preserve old content, queue index CAS versions in order, and keep Unicode boundaries intact',()=>{const s=setup();try{s.q.seed(sample,[]);const one={...sample,entries:[{...sample.entries[0],text:'长正文😀'.repeat(5000)}]};s.q.capture(one,'v2');const first=s.q.pending()!;for(const r of first.requests){expect(r.memory.body.length).toBeLessThanOrEqual(16000);expect(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(r.memory.body)).toBe(false)}expect(first.requests[0].memory.body).toContain('修订');s.q.capture({...sample,entries:[{...sample.entries[0],text:'再次修订'}]},'v3');s.q.acknowledge(first.id,first.sha256);const second=s.q.pending()!;const a=first.requests.find(x=>x.memory.project==='codex-history-index')!,b=second.requests.find(x=>x.memory.project==='codex-history-index')!;expect(a.memory.id).toBe(b.memory.id);expect(a.expectedVersion).toBe(0);expect(b.expectedVersion).toBe(1);expect(second.requests[0].memory.body).toContain('再次修订')}finally{s.close()}});
test('non-visible input rolls back the capture instead of advancing its checkpoint',()=>{const s=setup();try{s.q.seed(sample,[]);expect(()=>s.q.capture({...sample,entries:[{...sample.entries[0],text:'更新'},{id:'hidden',type:'reasoning',text:'internal',time:sample.createdAt}]},'bad')).toThrow('ARCHIVE_NON_VISIBLE_ITEM');expect(s.q.pending()).toBeNull();expect(s.q.needsCapture(sample.threadId,'bad')).toBe(true);expect(s.q.capture({...sample,entries:[{...sample.entries[0],text:'更新'}]},'good')).toBeGreaterThan(0)}finally{s.close()}});
test('partial cloud delivery replays safely, readback detects edits, and read-only actors cannot import',async()=>{const s=setup();const store=new MemoryStore(sqliteDatabase(':memory:'));const actor={namespace:'test',agent:'archive',projects:['codex-history','codex-history-index','codex-knowledge'],access:'rw' as const};try{s.q.capture(sample,'new');const batch=s.q.pending()!;await store.put(actor,batch.requests[0]);expect(await applyArchiveBatch(store,actor,batch.requests)).toBe(batch.requests.length);expect(await applyArchiveBatch(store,actor,batch.requests)).toBe(batch.requests.length);const r=batch.requests[0];await store.put(actor,{...r,operationId:crypto.randomUUID(),expectedVersion:1,memory:{...r.memory,body:'Manual edit must be preserved'}});await expect(applyArchiveBatch(store,actor,batch.requests)).rejects.toThrow('ARCHIVE_READBACK_MISMATCH');expect((await store.get(actor,r.memory.project,[r.memory.id]))[0].body).toBe('Manual edit must be preserved');await expect(applyArchiveBatch(store,{...actor,access:'ro'},batch.requests)).rejects.toThrow('READ_ONLY_CREDENTIAL')}finally{await store.close();s.close()}});
