import {test,expect} from 'bun:test';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ArchiveQueue,type ArchiveConversation} from '../src/archive';
const sample:ArchiveConversation={threadId:'example-thread',title:'测试会话',cwd:'example-project',createdAt:'2026-10-07T00:00:00Z',entries:[{id:'user-1',time:'2026-10-07T00:00:00Z',type:'user',text:'这是历史基线'}]};
function setup(){const dir=mkdtempSync(join(tmpdir(),'membridge-archive-'));const file=join(dir,'queue.db');const q=new ArchiveQueue(file);return {q,file,close(){this.q.close();if(!dir.startsWith(join(tmpdir(),'membridge-archive-')))throw new Error('INVALID_TEST_DIRECTORY');rmSync(dir,{recursive:true,force:true,maxRetries:5,retryDelay:50})}}}
test('baseline and unchanged snapshots produce no duplicate archive records',()=>{const s=setup();try{s.q.seed(sample,['aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa']);expect(s.q.capture(sample,'fingerprint-1')).toBe(0);expect(s.q.pending()).toBeNull();expect(s.q.needsCapture(sample.threadId,'fingerprint-1')).toBe(false)}finally{s.close()}});
test('new items remain durable offline, acknowledge only a matching batch, and deduplicate after restart',()=>{const s=setup();try{s.q.seed(sample,[]);const next={...sample,entries:[...sample.entries,{id:'assistant-1',time:'2026-10-07T00:01:00Z',type:'assistant',text:'Authorization: Bearer private-token-value'}]};expect(s.q.capture(next,'v2')).toBeGreaterThan(0);const pending=s.q.pending()!;expect(pending.requests[0].memory.body).not.toContain('private-token-value');s.q.close();s.q=new ArchiveQueue(s.file);expect(s.q.pending()?.id).toBe(pending.id);expect(s.q.capture(next,'v3')).toBe(0);expect(()=>s.q.acknowledge(pending.id,'wrong-hash')).toThrow();expect(s.q.pending()).not.toBeNull();s.q.acknowledge(pending.id,pending.sha256);expect(s.q.pending()).toBeNull()}finally{s.close()}});
test('revisions preserve old content, queue index CAS versions in order, and keep Unicode boundaries intact',()=>{const s=setup();try{s.q.seed(sample,[]);const one={...sample,entries:[{...sample.entries[0],text:'长正文😀'.repeat(5000)}]};s.q.capture(one,'v2');const first=s.q.pending()!;for(const r of first.requests){expect(r.memory.body.length).toBeLessThanOrEqual(16000);expect(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(r.memory.body)).toBe(false)}expect(first.requests[0].memory.body).toContain('修订');s.q.capture({...sample,entries:[{...sample.entries[0],text:'再次修订'}]},'v3');s.q.acknowledge(first.id,first.sha256);const second=s.q.pending()!;const a=first.requests.find(x=>x.memory.project==='codex-history-index')!,b=second.requests.find(x=>x.memory.project==='codex-history-index')!;expect(a.memory.id).toBe(b.memory.id);expect(a.expectedVersion).toBe(0);expect(b.expectedVersion).toBe(1);expect(second.requests[0].memory.body).toContain('再次修订')}finally{s.close()}});
